#!/bin/bash

cmake \
    -DCMAKE_INCLUDE_PATH=$PREFIX/include \
    -DCMAKE_LIBRARY_PATH=$PREFIX/lib \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DPIGLIT_BUILD_GLES1_TESTS:BOOL=OFF \
    -DPIGLIT_BUILD_GLES2_TESTS:BOOL=OFF \
    -DPIGLIT_BUILD_GLES3_TESTS:BOOL=OFF
make -j${CPU_COUNT}
make install
