{% set name = "piglit" %}

package:
  name: {{ name|lower }}
  {% if environ.get('GIT_DESCRIBE_TAG', '') != '' %}
  version: {{ '{}.{}+{}'.format(environ['GIT_DESCRIBE_TAG'][8:], environ['GIT_DESCRIBE_NUMBER'], environ['GIT_DESCRIBE_HASH']) }}
  {% endif %}

source:
  git_url: https://anongit.freedesktop.org/git/{{ name }}.git
  git_rev: master

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
    - mako 1.*
    - numpy >=1.10  # Only needed during build
    - python
    - six 1.*
    - waffle 1.5.*
  run:
    - mako 1.*
    - python
    - six 1.*
    - waffle >=1.5,<2

test:
  commands:
    - piglit run sanity results/sanity

# about:
#   home: http://www.mesa3d.org/
#   license: MIT
#   license_family: MIT
#   # It is strongly encouraged to include a license file in the package,
#   # (even if the license doesn't require it) using the license_file entry.
#   # See http://conda.pydata.org/docs/building/meta-yaml.html#license-file
# #   license_file: LICENSE.txt
#   summary: 'Mesa is an open-source implementation of the OpenGL specification'
# 
# #   description: |
# #     simplejson is a simple, fast, complete, correct and extensible
# #     JSON <http://json.org> encoder and decoder for Python 2.5+ and
# #     Python 3.3+. It is pure Python code with no dependencies, but includes
# #     an optional C extension for a serious speed boost.
#   dev_url: https://cgit.freedesktop.org/mesa/mesa/

extra:
  recipe-maintainers:
    - gqmelo
